version: "3.8"

services:
  # Service Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      target: dev
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - auth-service
      - product-service
      - order-service
    environment:
      - VITE_AUTH_SERVICE_URL=http://auth-service:3001
      - VITE_PRODUCT_SERVICE_URL=http://product-service:3000
      - VITE_ORDER_SERVICE_URL=http://order-service:3002

  # Service d'authentification
  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3001:3001"
    volumes:
      - ./services/auth-service:/app
      - /app/node_modules
    environment:
      - MONGODB_URI=mongodb://mongodb-auth:27017/auth
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongodb-auth

  # Service de produits
  product-service:
    build:
      context: ./services/product-service
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./services/product-service:/app
      - /app/node_modules
    environment:
      - MONGODB_URI=mongodb://mongodb-product:27017/products
      - AUTH_SERVICE_URL=http://auth-service:3001
      - JWT_SECRET=your_jwt_secret 
    depends_on:
      - mongodb-product

  # Service de commandes
  order-service:
    build:
      context: ./services/order-service
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3002:3002"
    volumes:
      - ./services/order-service:/app
      - /app/node_modules
    environment:
      - MONGODB_URI=mongodb://mongodb-order:27017/orders
      - VITE_AUTH_SERVICE_URL=http://auth-service:3001
      - VITE_PRODUCT_SERVICE_URL=http://product-service:3000
      - VITE_ORDER_SERVICE_URL=http://order-service:3002
      - JWT_SECRET=your_jwt_secret          

    depends_on:
      - mongodb-order

  # Base de données MongoDB pour auth-service
  mongodb-auth:
    image: mongo:4.4
    volumes:
      - mongo-auth-data:/data/db
    ports:
      - "27017:27017"

  # Base de données MongoDB pour product-service
  mongodb-product:
    image: mongo:4.4
    volumes:
      - mongo-product-data:/data/db
    ports:
      - "27018:27017"

  # Base de données MongoDB pour order-service
  mongodb-order:
    image: mongo:4.4
    volumes:
      - mongo-order-data:/data/db
    ports:
      - "27019:27017"

volumes:
  mongo-auth-data:
  mongo-product-data:
  mongo-order-data:
